<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LG2LKO2" failures="1" tests="5" name="retryTest" time="0.105" errors="0" timestamp="2020-01-05T12:21:15 IST">
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.025">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.0">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.005">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at reexecutefailtestcase.failtestcase.test1(failtestcase.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test2" time="0.005"/>
</testsuite> <!-- retryTest -->
